export const Routes = {
  backendRoot: "https://nussuwebsite-backend-77995810090f.herokuapp.com",
  index: "/",
  home: "/home",
  aboutUs: "/aboutus/aboutus",
  governance: "/aboutus/governance",
  history: "/aboutus/history",
  ourTeam: "/aboutus/ourteam",
  presidentMessage: "/aboutus/president-message",
  contact: "/contact",
  events: "/events",
  freshmen: "/freshmen",
  ourWork: "/our-work",
  services: "/services",
};
